# Generated by Django 5.2.3 on 2025-07-02 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Available_Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Lunes'), ('TUE', 'Martes'), ('WED', 'Miercoles'), ('THU', 'Jueves'), ('FRI', 'Viernes'), ('SAT', 'Sabado'), ('SUN', 'Domingo')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sure', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.BooleanField()),
                ('address', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specificity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('identity_card', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('id_available_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citations', to='CitasMedicas.available_times')),
                ('id_patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citations', to='CitasMedicas.patient')),
            ],
        ),
        migrations.AddField(
            model_name='available_times',
            name='id_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='CitasMedicas.doctor'),
        ),
        migrations.CreateModel(
            name='Medical_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.TextField()),
                ('treatment', models.TextField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('id_citation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_history', to='CitasMedicas.citation')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('route', models.FileField(blank=True, null=True, upload_to='medical_files/')),
                ('date_uploaded', models.DateField()),
                ('id_medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='CitasMedicas.medical_history')),
            ],
        ),
        migrations.AddField(
            model_name='available_times',
            name='id_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='CitasMedicas.office'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=50)),
                ('dose', models.TextField()),
                ('instructions', models.TextField()),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='prescriptions_pdfs/')),
                ('id_medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='CitasMedicas.medical_history')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='id_specificity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='CitasMedicas.specificity'),
        ),
        migrations.AddField(
            model_name='patient',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='CitasMedicas.user'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='CitasMedicas.user'),
        ),
    ]
